# Generated by Django 3.2.6 on 2021-09-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=7),
        ),
    ]
